{% set version = '0.7.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyr
  version: {{ version|replace("-", "_") }}

source:
  fn: tidyr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/tidyr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/tidyr/tidyr_{{ version }}.tar.gz
  sha256: b9c2430c72fe66c65a6aa83d835d3ea333ab09391c58ae0d57fd98e45088d1a1


  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, testthat, covr, gapminder, rmarkdown
requirements:
  build:
    - r-base
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - r-rcpp
    - r-dplyr >=0.7.0
    - r-glue
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble
    - r-tidyselect

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-dplyr >=0.7.0
    - r-glue
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble
    - r-tidyselect

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tidyr')"           # [not win]
    - "\"%R%\" -e \"library('tidyr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://tidyr.tidyverse.org, https://github.com/tidyverse/tidyr
  license: MIT + file LICENSE
  summary: An evolution of 'reshape2'. It's designed specifically for data tidying (not general
    reshaping or aggregating) and works well with 'dplyr' data pipelines.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: tidyr
# Title: Easily Tidy Data with 'spread()' and 'gather()' Functions
# Version: 0.7.1
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre")), person("Lionel", "Henry", , "lionel@rstudio.com", "aut"), person("RStudio", role = "cph") )
# Description: An evolution of 'reshape2'. It's designed specifically for data tidying (not general reshaping or aggregating) and works well with 'dplyr' data pipelines.
# Depends: R (>= 3.1.0)
# License: MIT + file LICENSE
# LazyData: true
# Imports: dplyr (>= 0.7.0), glue, magrittr, purrr, rlang, Rcpp, stringi, tibble, tidyselect
# URL: http://tidyr.tidyverse.org, https://github.com/tidyverse/tidyr
# BugReports: https://github.com/tidyverse/tidyr/issues
# Suggests: knitr, testthat, covr, gapminder, rmarkdown
# VignetteBuilder: knitr
# LinkingTo: Rcpp
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-08-24 14:15:41 UTC; lionel
# Author: Hadley Wickham [aut, cre], Lionel Henry [aut], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-09-01 15:15:47 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
