{% set version = '0.8.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyr/tidyr_{{ version }}.tar.gz
  sha256: 3d3e2821c3eb711b5eebe26b880e6acfe5444d5dc69fb21761f4cd5953700511

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, gapminder, knitr, rmarkdown, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp
    - r-dplyr >=0.7.0
    - r-glue
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble
    - r-tidyselect

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-dplyr >=0.7.0
    - r-glue
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble
    - r-tidyselect

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tidyr')"           # [not win]
    - "\"%R%\" -e \"library('tidyr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://tidyr.tidyverse.org, https://github.com/tidyverse/tidyr
  license: MIT + file LICENSE
  summary: An evolution of 'reshape2'. It's designed specifically for data tidying (not general
    reshaping or aggregating) and works well with 'dplyr' data pipelines.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: tidyr
# Title: Easily Tidy Data with 'spread()' and 'gather()' Functions
# Version: 0.8.1
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre")), person("Lionel", "Henry", , "lionel@rstudio.com", "aut"), person("RStudio", role = "cph") )
# Description: An evolution of 'reshape2'. It's designed specifically for data tidying (not general reshaping or aggregating) and works well with 'dplyr' data pipelines.
# License: MIT + file LICENSE
# URL: http://tidyr.tidyverse.org, https://github.com/tidyverse/tidyr
# BugReports: https://github.com/tidyverse/tidyr/issues
# Depends: R (>= 3.1)
# Imports: dplyr (>= 0.7.0), glue, magrittr, purrr, Rcpp, rlang, stringi, tibble, tidyselect
# Suggests: covr, gapminder, knitr, rmarkdown, testthat
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2018-05-09 14:59:50 UTC; hadley
# Author: Hadley Wickham [aut, cre], Lionel Henry [aut], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-05-18 11:17:55 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
