travis:
  secure:
    BINSTAR_TOKEN: ebGBSuKM4+VsW9y/1IJt7dPRYwuD9pPE6PfbNUxXhf2lDCGqAC01ZND5kpEXCrYzUyVpuylnXERqqldNchuIoXbuK62VI1CDCH8P5Il+dSWLSL2c3ytQTIL4ad5YpyQP3saSjbp7XhgjEiJ+F6e6sT0YAO838Pg9rcZyvTlR1LC34TuS3eUOXW1DltxU48ZZUa5tFpaSZ2ZpckqCHvh6JvU2x2fFA8oOOvEHwucxvlbEwrFS42UEgHQevQCp6aVL2qUqNDh7qZ/YmSjOXVb+pukxuCFheyg43YCRxIDDlwvpixKhQTo3HD7bFOj5hv0AG3EC6r4in9/SyJSTvHPFcWoxww95SuA0w3uAP1kbhp2Zz6k1Ys4hF29xWwE48SG42sVBSdG5IpaJL6frX7kuL2uQYR7jKZty8uRNPTJBvEbeL5z8NDQqgv7NIV4NgP5Bu9TdvhcJnZ/XSsJFkHwYdV2Di7UJ+DRjQ2mERM2ciGSqL+8H5G90RxHb4eJLKcoVWK4ResShGXNnOQY6C2oso8DCmNJ//lrhVRtkNkZj1YvYf8FYqhupKRqZwbdG1fs8IKTndvfDZ1AzhHiRtN3vpbN0wdmDMFtahY4YU8Y2yWJnF0x5lQnPC93ENlYaevYcvAd3iH/S0XzobD118U9aNgerNlKZMbHyBAW/zNwXz3w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
