travis:
  secure:
    BINSTAR_TOKEN: ldLdJ6p5am/mfJk8aoludrsVVRJly/w6rpWrTQNT7qOOAEuvV3R5r3hcZOP2wVaoiyFJ1C1PAPkW0FIcpx1TGeZOuS1cuu6gIMzB6+iOuM1mRMsdYxoDZiYh5gVoO7mo922jSeN8UU9/W//ymEjPkQHOSk6HtOfMefkVEDSlQtEBw9EeQ8m4Uth6332lPLTe3IMpiQc6hyM0JBJFWfmQfPbra9PJSXX7zhBGO/Xm8JIfBl+mZ96wmYiKLWTrYyY/EK5rwlrostso8zDmFdmBCsf3pJRErvlXHJ8BVn+mKyhtEZaNwhIe5OAY64r9XCs+SjDPR5bbNewf7joLDZTcvx8zQ5D9zyRdIwVpeb3W5rk0zNDqH4BzpVtwn+oGAbbMQrUyBkAUYm6JWZDiK2sLoQFqeNgvWjEjYtXGMN/YQGSu5uUk9I4KH6H1Ns7r1atuTE1u7ZsC5c/4mtvd9iGlqsdaEDx8fRHaiylhY7pmfbZHWbB3H757MwNHtukdqYfplY4VTlY0iDuRufqZmKUl+nddG4wW0bntUv4IaC4ZzfHzJH6ZXlKGitEfhMnDmIRSYkVPo7fg9WwL+pirdrwMYxUZfil6s4Qh4EzXCCUUDnEyhy59jU4Da27Wq90MNqDpsK4CIbuOjnKlszE3FaMuSDUZBV8GOFuqQ/+l1QeiiqE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
